### ISSUE TITLE
ValueError: could not broadcast input array from shape (736,776,3) into shape (776,736,3)

### ISSUE THREAD

**Issue by bullionist** [mwydmuch/ZoomVideoComposer#11]
Once I run the video zoom compressor, I am getting the below error

```
Reading 8 image files ...
Blending 8 images ...
Traceback (most recent call last):
File "/content/ZoomVideoComposer/zoom_video_composer.py", line 344, in <module>
zoom_video_composer_cli()
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/content/ZoomVideoComposer/zoom_video_composer.py", line 219, in zoom_video_composer_cli
zoom_video_composer(
File "/content/ZoomVideoComposer/zoom_video_composer.py", line 296, in zoom_video_composer
images = blend_images(images, margin, zoom, resampling_func)
File "/content/ZoomVideoComposer/helpers.py", line 288, in blend_images
image.paste(inner_image, margin, margin)
File "/content/ZoomVideoComposer/helpers.py", line 73, in paste
self.image[y : y + image.height, x : x + image.width] = image.image
ValueError: could not broadcast input array from shape (736,776,3) into shape (776,736,3)
```

Here are the settings I am using

```
!python zoom_video_composer.py upload \
--output results/zoom.mp4 \
--zoom 2.0 \
--duration 30.0 \
--height 1456 \
--width 816 \
--direction outin
```
Facing the same running it on my mac and Google Colabs.
Appreciate your help, thanks!

**Comment by mwydmuch** [comment]
Hi, @bullionist, thank you for reporting. Looks like we introduced a bug in the last release, I will fix it soon (like in 2h). For a moment you can use the previous version or use the old image engine adding `--image-engine pil` argument.

**Comment by mwydmuch** [comment]
Ok, it's fixed. You can download the newest version, the image processing should be ~30% faster with this one. Once again thanks for reporting the bug!
